name: 'Build'

on:
  push:
    tags: [ '*.*.*' ]

jobs:
  test:
    uses: './.github/workflows/test.yml'
    permissions:
      contents: 'read'

  build:
    needs: 'test'
    uses: 'trexx/actions/.github/workflows/build.yml@main'
    secrets: 'inherit'
    permissions:
      contents: read
      packages: write
